// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojxszcyngeppqmstpwjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qeHN6Y3luZ2VwcHFtc3Rwd2p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDkxOTcsImV4cCI6MjA2MDgyNTE5N30.LGn5wZMXP9Ejwlq57hy0CFiNiguqBowVjMnAGM02Gu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);